import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import type { AmenityAvailability, CoolingComfortSpotRecord, FacilityEnvironment, Language } from '../types';
import { calculateDistanceMeters, formatDistance } from '../utils/facilityUtils';

type View = 'find' | 'map' | 'directory' | 'amenities' | 'opening' | 'environment' | 'insights' | 'quality' | 'notes';
type Summary = { dataQuality: Record<string, unknown[]> };
type Requirement = 'airConditioningAvailability' | 'seatingAvailability' | 'drinkingWaterAvailability' | 'toiletAvailability' | 'accessibleSeatingAvailability' | 'indoor';
const EMPTY = '—'; const amenityKeys = ['airConditioningAvailability', 'fanAvailability', 'toiletAvailability', 'seatingAvailability', 'drinkingWaterAvailability', 'accessibleSeatingAvailability'] as const;
const amenity = (key: typeof amenityKeys[number], zh: boolean) => ({ airConditioningAvailability: zh ? '冷氣' : 'Air conditioning', fanAvailability: zh ? '電風扇' : 'Fan', toiletAvailability: zh ? '廁所' : 'Toilet', seatingAvailability: zh ? '座位' : 'Seating', drinkingWaterAvailability: zh ? '飲水設施' : 'Drinking water', accessibleSeatingAvailability: zh ? '無障礙座位' : 'Accessible seating' })[key];
const availability = (value: AmenityAvailability, zh: boolean) => ({ yes: zh ? '有' : 'Yes', no: zh ? '無' : 'No', conditional: zh ? '需確認' : 'Conditional', unknown: zh ? '未提供' : 'Unknown' })[value];
const environment = (value: FacilityEnvironment, zh: boolean) => ({ indoor: zh ? '室內' : 'Indoor', outdoor: zh ? '戶外' : 'Outdoor', mixed: zh ? '混合' : 'Mixed', unknown: zh ? '未提供' : 'Unknown' })[value];

export function CoolingComfortSpotsDashboard({ language }: { language: Language }) {
  const zh = language === 'zh'; const [records, setRecords] = useState<CoolingComfortSpotRecord[] | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [view, setView] = useState<View>('find');
  const [district, setDistrict] = useState(''); const [env, setEnv] = useState<FacilityEnvironment | ''>(''); const [search, setSearch] = useState(''); const [needs, setNeeds] = useState<Requirement[]>([]); const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null); const [radius, setRadius] = useState(0); const [page, setPage] = useState(1);
  useEffect(() => { fetch('/data/cooling-comfort-spots/records.json').then((r) => r.ok ? r.json() : Promise.reject()).then(setRecords).catch(() => setRecords([])); fetch('/data/cooling-comfort-spots/summary.json').then((r) => r.ok ? r.json() : Promise.reject()).then(setSummary).catch(() => setSummary(null)); }, []);
  const districts = useMemo(() => [...new Set((records ?? []).map((r) => r.districtName).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const withDistance = useMemo(() => (records ?? []).map((record) => ({ ...record, distance: location && record.hasValidCoordinates && record.latitude !== null && record.longitude !== null ? calculateDistanceMeters(location.latitude, location.longitude, record.latitude, record.longitude) : null, matches: needs.filter((need) => need === 'indoor' ? record.environment === 'indoor' : record[need] === 'yes').length })), [records, location, needs]);
  const filtered = useMemo(() => withDistance.filter((r) => !district || r.districtName === district).filter((r) => !env || r.environment === env).filter((r) => !radius || (r.distance !== null && r.distance <= radius)).filter((r) => !search || [r.name, r.districtName, r.address, r.openingHoursRaw, r.highlights].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => b.matches - a.matches || (a.distance ?? Infinity) - (b.distance ?? Infinity) || a.name.localeCompare(b.name, 'zh-Hant')), [withDistance, district, env, radius, search]);
  const mapMarkers = useMemo(() => {
    const valid = filtered.filter((r) => r.hasValidCoordinates && r.latitude !== null && r.longitude !== null);
    if (valid.length <= 150) return valid.map((record) => ({ id: record.id, latitude: record.latitude!, longitude: record.longitude!, records: [record] }));
    const clusters = new Map<string, typeof valid>();
    valid.forEach((record) => { const key = `${Math.round(record.latitude! * 100) / 100}|${Math.round(record.longitude! * 100) / 100}`; clusters.set(key, [...(clusters.get(key) ?? []), record]); });
    return [...clusters.entries()].map(([key, grouped]) => { const [latitude, longitude] = key.split('|').map(Number); return { id: key, latitude, longitude, records: grouped }; });
  }, [filtered]);
  const pages = Math.max(1, Math.ceil(filtered.length / 12)); const rows = filtered.slice((Math.min(page, pages) - 1) * 12, Math.min(page, pages) * 12); const reset = () => setPage(1);
  const toggle = (need: Requirement) => { setNeeds((all) => all.includes(need) ? all.filter((item) => item !== need) : [...all, need]); reset(); };
  const useNearby = () => navigator.geolocation?.getCurrentPosition((position) => { setLocation({ latitude: position.coords.latitude, longitude: position.coords.longitude }); reset(); });
  const sections: Array<{ label: string; views: Array<[View, string]> }> = [
    { label: zh ? '探索' : 'Explore', views: [['find', zh ? '附近搜尋' : 'Nearby search'], ['map', zh ? '地圖' : 'Map'], ['directory', zh ? '設施目錄' : 'Directory']] },
    { label: zh ? '服務條件' : 'Facilities', views: [['amenities', zh ? '設備' : 'Amenities'], ['opening', zh ? '開放時間' : 'Opening hours'], ['environment', zh ? '室內／戶外' : 'Environment']] },
    { label: zh ? '資料洞察' : 'Insights', views: [['insights', zh ? '摘要' : 'Overview']] },
    { label: zh ? '資料說明' : 'About', views: [['quality', zh ? '資料品質' : 'Data quality'], ['notes', zh ? '使用說明' : 'Data notes']] },
  ];
  const activeSection = sections.findIndex((section) => section.views.some(([key]) => key === view));
  const download = () => { const quote = (value: string) => `"${value.replace(/"/g, '""')}"`; const headings = [zh ? '名稱' : 'Name', zh ? '環境' : 'Environment', zh ? '行政區' : 'District', zh ? '地址' : 'Address', zh ? '開放時間' : 'Opening hours', ...amenityKeys.map((key) => amenity(key, zh))]; const csv = [headings, ...filtered.map((r) => [r.name, environment(r.environment, zh), r.districtName, r.address, r.openingHoursRaw, ...amenityKeys.map((key) => availability(r[key], zh))])].map((row) => row.map(quote).join(',')).join('\r\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8' })); anchor.download = 'taipei-cooling-comfort-spots.csv'; anchor.click(); URL.revokeObjectURL(anchor.href); };
  const chart = (items: Array<[string, number]>) => <div className="dashboard-chart">{items.map(([label, count]) => <div className="bar-row" key={label}><span>{label}</span><div><i style={{ width: `${count / Math.max(filtered.length, 1) * 100}%` }} /></div><strong>{count}</strong></div>)}</div>;
  const requirementLabels: Array<[Requirement, string]> = [['airConditioningAvailability', zh ? '冷氣' : 'Air conditioning'], ['seatingAvailability', zh ? '座位' : 'Seating'], ['drinkingWaterAvailability', zh ? '飲水設施' : 'Drinking water'], ['toiletAvailability', zh ? '廁所' : 'Toilet'], ['accessibleSeatingAvailability', zh ? '無障礙座位' : 'Accessible seating'], ['indoor', zh ? '偏好室內' : 'Prefer indoor']];
  if (!records) return <section className="bulky-dashboard"><p>{zh ? '載入涼適點資料中…' : 'Loading cooling-spot data…'}</p></section>;
  return <section className="bulky-dashboard cooling-dashboard" aria-label={zh ? '臺北市涼適點' : 'Taipei Cooling & Comfort Spots'}><nav className="cooling-section-tabs" aria-label={zh ? '涼適點主要分區' : 'Cooling spot sections'}>{sections.map((section, index) => <button key={section.label} type="button" className={activeSection === index ? 'active' : ''} aria-pressed={activeSection === index} onClick={() => setView(section.views[0][0])}>{section.label}</button>)}</nav><nav className="cooling-subtabs" aria-label={sections[activeSection]?.label}>{sections[activeSection]?.views.map(([key, label]) => <button key={key} type="button" className={view === key ? 'active' : ''} aria-pressed={view === key} onClick={() => setView(key)}>{label}</button>)}</nav>
    <div className="bulky-filters"><label>{zh ? '行政區' : 'District'}<select value={district} onChange={(e) => { setDistrict(e.target.value); reset(); }}><option value="">{zh ? '全部' : 'All'}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label><label>{zh ? '室內／戶外' : 'Environment'}<select value={env} onChange={(e) => { setEnv(e.target.value as FacilityEnvironment); reset(); }}><option value="">{zh ? '全部' : 'All'}</option>{(['indoor', 'outdoor', 'mixed', 'unknown'] as FacilityEnvironment[]).map((item) => <option value={item} key={item}>{environment(item, zh)}</option>)}</select></label><label>{zh ? '名稱、地址或關鍵字' : 'Name, address, or keyword'}<input value={search} onChange={(e) => { setSearch(e.target.value); reset(); }} /></label><label>{zh ? '附近範圍' : 'Nearby radius'}<select value={radius} disabled={!location} onChange={(e) => { setRadius(Number(e.target.value)); reset(); }}><option value="0">{zh ? '不限' : 'Any'}</option><option value="500">500 m</option><option value="1000">1 km</option><option value="2000">2 km</option><option value="5000">5 km</option></select></label><button type="button" onClick={useNearby}>{zh ? '使用目前位置' : 'Use my location'}</button><button type="button" onClick={download}>{zh ? '下載篩選 CSV' : 'Download filtered CSV'}</button></div>
    <div className="dashboard-message"><strong>{zh ? '舒適需求' : 'Comfort Needs'}</strong><div className="quick-filter-row">{requirementLabels.map(([key, label]) => <button type="button" className={needs.includes(key) ? 'active' : ''} aria-pressed={needs.includes(key)} onClick={() => toggle(key)} key={key}>{label}</button>)}</div>{needs.length > 0 && <p>{zh ? `已依需求符合度排序；每筆結果顯示符合 ${needs.length} 項需求中的數量，並非品質或安全評分。` : `Sorted by requested amenities. The match count is not a quality or safety score.`}</p>}</div>
    {view === 'find' && <><div className="dashboard-cards">{[[zh ? '符合結果' : 'Matching spots', filtered.length], [zh ? '有冷氣' : 'With air conditioning', filtered.filter((r) => r.airConditioningAvailability === 'yes').length], [zh ? '有飲水設施' : 'With drinking water', filtered.filter((r) => r.drinkingWaterAvailability === 'yes').length], [zh ? '有廁所與座位' : 'With toilet and seating', filtered.filter((r) => r.toiletAvailability === 'yes' && r.seatingAvailability === 'yes').length]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="cooling-cards">{rows.map((r) => <article key={r.id}><h3>{r.name || EMPTY}</h3><p>{environment(r.environment, zh)} · {r.districtName || EMPTY}{r.distance !== null && ` · ${formatDistance(r.distance, language)}`}</p><p>{r.address || EMPTY}</p><p>{amenityKeys.map((key) => `${amenity(key, zh)}：${availability(r[key], zh)}`).join(' · ')}</p>{needs.length > 0 && <strong>{zh ? `符合 ${r.matches} / ${needs.length} 項需求` : `Matches ${r.matches} of ${needs.length} requested amenities`}</strong>}<p>{r.openingHoursRaw || EMPTY}</p>{r.phone && <a href={`tel:${r.phone.replace(/[^\d+]/g, '')}`}>{zh ? '撥打電話' : 'Call'}：{r.phone}</a>}</article>)}</div></>}
    {view === 'map' && <div className="cooling-map"><MapContainer center={[25.0478, 121.5319]} zoom={12} scrollWheelZoom><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{mapMarkers.map((marker) => <CircleMarker key={marker.id} center={[marker.latitude, marker.longitude]} radius={marker.records.length > 1 ? Math.min(16, 7 + marker.records.length / 4) : marker.records[0].environment === 'indoor' ? 7 : 5} pathOptions={{ color: marker.records.length > 1 ? '#7c3aed' : marker.records[0].environment === 'indoor' ? '#1d4ed8' : '#c2410c' }}><Popup>{marker.records.length > 1 ? <><strong>{marker.records.length} {zh ? '個涼適點' : 'cooling spots'}</strong><ul>{marker.records.slice(0, 8).map((r) => <li key={r.id}>{r.name}</li>)}</ul></> : <><strong>{marker.records[0].name}</strong><br />{environment(marker.records[0].environment, zh)} · {marker.records[0].districtName}<br />{marker.records[0].address}<br />{marker.records[0].openingHoursRaw || EMPTY}</>}</Popup></CircleMarker>)}</MapContainer><p>{zh ? `${mapMarkers.length < filtered.filter((r) => r.hasValidCoordinates).length ? '大量結果以網格叢集呈現；縮小篩選範圍可查看個別點位。' : ''} 使用官方座標；沒有有效座標的紀錄仍可在設施目錄中查詢。` : `${mapMarkers.length < filtered.filter((r) => r.hasValidCoordinates).length ? 'Large result sets are shown as grid clusters; narrow filters to see individual points. ' : ''}Official coordinates are used. Records without valid coordinates remain in the directory.`}</p></div>}
    {view === 'directory' && <><div className="directory-table-wrap"><table><thead><tr><th>{zh ? '名稱' : 'Name'}</th><th>{zh ? '環境' : 'Environment'}</th><th>{zh ? '行政區' : 'District'}</th><th>{zh ? '地址' : 'Address'}</th><th>{zh ? '開放時間' : 'Opening hours'}</th><th>{zh ? '設施' : 'Amenities'}</th><th>{zh ? '電話' : 'Telephone'}</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><td>{r.name || EMPTY}</td><td>{environment(r.environment, zh)}</td><td>{r.districtName || EMPTY}</td><td>{r.address || EMPTY}<button className="copy-button" type="button" onClick={() => navigator.clipboard?.writeText(r.address)}>{zh ? '複製' : 'Copy'}</button></td><td><details><summary>{r.openingHoursRaw || EMPTY}</summary><p>{zh ? `解析信心：${r.parsedOpeningHours.parseConfidence}` : `Parse confidence: ${r.parsedOpeningHours.parseConfidence}`}</p></details></td><td>{amenityKeys.map((key) => `${amenity(key, zh)} ${availability(r[key], zh)}`).join('；')}</td><td>{r.phone ? <a href={`tel:${r.phone.replace(/[^\d+]/g, '')}`}>{r.phone}</a> : EMPTY}</td></tr>)}</tbody></table></div><div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>{zh ? '上一頁' : 'Previous'}</button><span>{Math.min(page, pages)} / {pages}</span><button disabled={page >= pages} onClick={() => setPage(page + 1)}>{zh ? '下一頁' : 'Next'}</button></div></>}
    {view === 'amenities' && chart(amenityKeys.map((key) => [amenity(key, zh), filtered.filter((r) => r[key] === 'yes').length]))}
    {view === 'opening' && <div className="dashboard-message"><p>{zh ? `有 ${filtered.filter((r) => r.parsedOpeningHours.schedules.length).length} 筆紀錄含可辨識的時段。時段是由來源文字保守解析，請以原始開放時間與場館公告為準。` : `${filtered.filter((r) => r.parsedOpeningHours.schedules.length).length} records contain recognizable periods. Times are conservatively derived from source text; check the original hours and venue notices.`}</p></div>}
    {view === 'environment' && chart((['indoor', 'outdoor', 'mixed', 'unknown'] as FacilityEnvironment[]).map((key) => [environment(key, zh), filtered.filter((r) => r.environment === key).length]))}
    {view === 'insights' && <><div className="dashboard-cards">{[[zh ? '冷氣與飲水設施' : 'AC + drinking water', filtered.filter((r) => r.airConditioningAvailability === 'yes' && r.drinkingWaterAvailability === 'yes').length], [zh ? '冷氣、飲水、廁所與座位' : 'AC + water + toilet + seating', filtered.filter((r) => r.airConditioningAvailability === 'yes' && r.drinkingWaterAvailability === 'yes' && r.toiletAvailability === 'yes' && r.seatingAvailability === 'yes').length], [zh ? '有無障礙座位' : 'Accessible seating listed', filtered.filter((r) => r.accessibleSeatingAvailability === 'yes').length], [zh ? '有效座標' : 'Valid coordinates', filtered.filter((r) => r.hasValidCoordinates).length]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><p className="dashboard-message">{zh ? '以上是來源列示的設施組合與資料涵蓋情形，不代表現場可用性、安全性或熱風險評比。' : 'These describe listed amenity combinations and dataset coverage, not current availability, safety, or a heat-risk rating.'}</p></>}
    {view === 'quality' && <div className="quality-grid">{Object.entries(summary?.dataQuality ?? {}).map(([key, value]) => <article key={key}><span>{key}</span><strong>{value.length}</strong></article>)}</div>}
    {view === 'notes' && <div className="dashboard-message"><p>{zh ? '本資料為臺北市轄內室內及戶外涼適場所的公開資訊，包含地址、座標、開放時間與設備欄位。它不保證場所目前開放、冷氣或電風扇運作、座位可用、飲水設施或廁所可使用，也不代表緊急避暑收容或醫療服務。請向現場或管理單位確認。' : 'This dataset provides public information about indoor and outdoor cooling and comfort locations in Taipei. It does not guarantee current opening, functioning equipment, available seating, usable drinking water or toilets, emergency shelter status, or medical service. Confirm with the site or managing organization.'}</p></div>}
  </section>;
}
