import { useEffect, useMemo, useState } from 'react';
import type { BookingStatus, Language, PublicSchoolSportsVenueRecord, SportType } from '../types';

type View = 'find' | 'schools' | 'sports' | 'opening' | 'booking' | 'districts' | 'quality' | 'notes';
type Summary = { dataQuality: Record<string, unknown[]> };
const EMPTY = '—';
const sports: Array<[SportType, string, string]> = [['badminton', '羽球', 'Badminton'], ['basketball', '籃球', 'Basketball'], ['pickleball', '匹克球', 'Pickleball'], ['volleyball', '排球', 'Volleyball'], ['tennis', '網球', 'Tennis'], ['table_tennis', '桌球', 'Table tennis'], ['track', '田徑／跑道', 'Track and field'], ['football', '足球', 'Football / soccer']];
const bookingLabel = (value: BookingStatus, zh: boolean) => ({ official_booking_link: zh ? '官方預約連結' : 'Official booking link', booking_information_in_source: zh ? '來源含預約資訊' : 'Booking information in source', contact_school: zh ? '請向學校確認' : 'Contact school to confirm', unknown: zh ? '未確認' : 'Unknown' })[value];

export function PublicSchoolSportsVenuesDashboard({ language }: { language: Language }) {
  const zh = language === 'zh'; const [records, setRecords] = useState<PublicSchoolSportsVenueRecord[] | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [view, setView] = useState<View>('find');
  const [sport, setSport] = useState<SportType | ''>(''); const [district, setDistrict] = useState(''); const [booking, setBooking] = useState<BookingStatus | ''>(''); const [day, setDay] = useState(''); const [time, setTime] = useState(''); const [search, setSearch] = useState(''); const [sort, setSort] = useState<'schoolName' | 'districtName' | 'bookingStatus'>('schoolName'); const [page, setPage] = useState(1);
  useEffect(() => { fetch('/data/public-school-sports-venues/records.json').then((r) => r.ok ? r.json() : Promise.reject()).then(setRecords).catch(() => setRecords([])); fetch('/data/public-school-sports-venues/summary.json').then((r) => r.ok ? r.json() : Promise.reject()).then(setSummary).catch(() => setSummary(null)); }, []);
  const districts = useMemo(() => [...new Set((records ?? []).map((r) => r.districtName).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const filtered = useMemo(() => (records ?? []).filter((r) => !sport || r.detectedSports.includes(sport)).filter((r) => !district || r.districtName === district).filter((r) => !booking || r.bookingStatus === booking).filter((r) => !day || r.parsedSchedules.some((s) => s.days.includes(day))).filter((r) => !time || r.parsedSchedules.some((s) => s.startTime && s.endTime && s.startTime <= time && s.endTime >= time)).filter((r) => !search || [r.schoolName, r.districtName, r.agencyCode, r.campusOpeningText, r.detectedFacilityLabels.join(' ')].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => String(a[sort]).localeCompare(String(b[sort]), 'zh-Hant')), [records, sport, district, booking, day, time, search, sort]);
  const pages = Math.max(1, Math.ceil(filtered.length / 10)); const pageRows = filtered.slice((Math.min(page, pages) - 1) * 10, Math.min(page, pages) * 10); const reset = () => setPage(1);
  const labels: Array<[View, string]> = [['find', zh ? '尋找運動場地' : 'Find a Sports Venue'], ['schools', zh ? '學校' : 'Schools'], ['sports', zh ? '運動與設施' : 'Sports and Facilities'], ['opening', zh ? '校園開放時間' : 'Campus Opening Times'], ['booking', zh ? '預約資訊' : 'Booking Information'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['quality', zh ? '資料品質' : 'Data Quality'], ['notes', zh ? '資料說明' : 'Data Notes']];
  const download = () => { const q = (v: string) => `"${v.replace(/"/g, '""')}"`; const columns = [zh ? '校名' : 'School', zh ? '行政區' : 'District', zh ? '郵遞區號' : 'Postal code', zh ? '機關代碼' : 'Agency code', zh ? '偵測運動' : 'Detected sports', zh ? '校園場地開放時間' : 'Campus opening information', zh ? '預約資訊狀態' : 'Booking-information status']; const csv = [columns, ...filtered.map((r) => [r.schoolName, r.districtName, r.postalCode, r.agencyCode, r.detectedFacilityLabels.join('、'), r.campusOpeningRaw, bookingLabel(r.bookingStatus, zh)])].map((row) => row.map(q).join(',')).join('\r\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8' })); a.download = 'taipei-public-school-sports-venues.csv'; a.click(); URL.revokeObjectURL(a.href); };
  const chart = (items: string[], count: (item: string) => number) => <div className="dashboard-chart">{items.map((item) => <div className="bar-row" key={item}><span>{item}</span><div><i style={{ width: `${count(item) / Math.max(filtered.length, 1) * 100}%` }} /></div><strong>{count(item)}</strong></div>)}</div>;
  if (!records) return <section className="bulky-dashboard"><p>{zh ? '載入校園場地開放資料中…' : 'Loading public school campus-opening data…'}</p></section>;
  return <section className="bulky-dashboard" aria-label={zh ? '公立學校運動場地搜尋' : 'Public School Sports Venue Search'}><nav className="module-view-tabs" aria-label={zh ? '公立學校運動場地搜尋' : 'Public School Sports Venue Search'}>{labels.map(([key, label]) => <button type="button" key={key} className={view === key ? 'active' : ''} aria-pressed={view === key} onClick={() => setView(key)}>{label}</button>)}</nav>
    <div className="bulky-filters"><label>{zh ? '運動' : 'Sport'}<select value={sport} onChange={(e) => { setSport(e.target.value as SportType); reset(); }}><option value="">{zh ? '不限（未列明亦可搜尋）' : 'All (including not specified)'}</option>{sports.map(([id, cn, en]) => <option value={id} key={id}>{zh ? cn : en}</option>)}</select></label><label>{zh ? '行政區' : 'District'}<select value={district} onChange={(e) => { setDistrict(e.target.value); reset(); }}><option value="">{zh ? '全部' : 'All'}</option>{districts.map((v) => <option key={v}>{v}</option>)}</select></label><label>{zh ? '偏好日' : 'Preferred day'}<select value={day} onChange={(e) => { setDay(e.target.value); reset(); }}><option value="">{zh ? '不限' : 'Any'}</option><option value="weekdays">{zh ? '平日' : 'Weekdays'}</option><option value="weekends">{zh ? '週末／假日' : 'Weekends / holidays'}</option></select></label><label>{zh ? '偏好時間' : 'Preferred time'}<input type="time" value={time} onChange={(e) => { setTime(e.target.value); reset(); }} /></label><label>{zh ? '預約資訊' : 'Booking information'}<select value={booking} onChange={(e) => { setBooking(e.target.value as BookingStatus); reset(); }}><option value="">{zh ? '全部' : 'All'}</option>{(['official_booking_link', 'booking_information_in_source', 'contact_school', 'unknown'] as BookingStatus[]).map((v) => <option value={v} key={v}>{bookingLabel(v, zh)}</option>)}</select></label><label>{zh ? '學校名稱或關鍵字' : 'School name or keyword'}<input value={search} onChange={(e) => { setSearch(e.target.value); reset(); }} placeholder={zh ? '校名、行政區、機關代碼或開放文字' : 'School, district, agency code, or opening text'} /></label><button type="button" onClick={download}>{zh ? '下載篩選 CSV' : 'Download filtered CSV'}</button></div>
    {view === 'find' && <><div className="dashboard-cards">{[[zh ? '符合結果' : 'Matching schools', filtered.length], [zh ? '涵蓋行政區' : 'Districts covered', new Set(filtered.map((r) => r.districtName)).size], [zh ? '含可解析時段' : 'Parseable schedules', filtered.filter((r) => r.parsedSchedules.length).length], [zh ? '需向學校確認' : 'Contact school to confirm', filtered.filter((r) => r.bookingStatus === 'contact_school').length]].map(([l, v]) => <article key={String(l)}><span>{l}</span><strong>{v}</strong></article>)}</div><p className="dashboard-message">{zh ? '運動標籤僅在來源文字明確出現時顯示；本資料的校園開放資訊不代表可預約、目前有空檔或具備特定球場。' : 'Sports are shown only when explicitly found in source text. Campus-opening information does not establish reservability, current availability, or a particular court.'}</p></>}
    {view === 'schools' && <><div className="bulky-directory-toolbar"><label>{zh ? '排序' : 'Sort'}<select value={sort} onChange={(e) => { setSort(e.target.value as typeof sort); reset(); }}><option value="schoolName">{zh ? '校名' : 'School name'}</option><option value="districtName">{zh ? '行政區' : 'District'}</option><option value="bookingStatus">{zh ? '預約資訊' : 'Booking information'}</option></select></label><span>{filtered.length} {zh ? '筆' : 'records'}</span></div><div className="directory-table-wrap"><table><thead><tr><th>{zh ? '學校' : 'School'}</th><th>{zh ? '行政區' : 'District'}</th><th>{zh ? '偵測運動' : 'Detected sports'}</th><th>{zh ? '校園開放資訊' : 'Campus opening information'}</th><th>{zh ? '預約資訊' : 'Booking information'}</th></tr></thead><tbody>{pageRows.map((r) => <tr key={r.id}><td>{r.schoolName || EMPTY}<button className="copy-button" type="button" onClick={() => navigator.clipboard?.writeText(r.schoolName)}>{zh ? '複製' : 'Copy'}</button><small>{r.agencyCode}</small></td><td>{r.districtName || EMPTY}</td><td>{r.detectedFacilityLabels.join('、') || (zh ? '未列明運動' : 'Sport not specified')}</td><td><details><summary>{r.campusOpeningText || EMPTY}</summary><p>{r.campusOpeningRaw || EMPTY}</p></details></td><td>{bookingLabel(r.bookingStatus, zh)}{r.bookingStatus === 'contact_school' && <small>{zh ? '請向學校確認預約方式與實際場地。' : 'Contact the school to confirm reservations and facilities.'}</small>}</td></tr>)}</tbody></table></div><div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>{zh ? '上一頁' : 'Previous'}</button><span>{Math.min(page, pages)} / {pages}</span><button disabled={page >= pages} onClick={() => setPage(page + 1)}>{zh ? '下一頁' : 'Next'}</button></div></>}
    {view === 'sports' && <>{chart(sports.map(([, cn, en]) => zh ? cn : en), (label) => { const item = sports.find(([, cn, en]) => (zh ? cn : en) === label); return item ? filtered.filter((r) => r.detectedSports.includes(item[0])).length : 0; })}<p className="dashboard-message">{zh ? '未出現在來源文字的運動不會被推定；尤其羽球、網球或多功能場地不會被視為匹克球場。' : 'Sports absent from source text are not inferred; badminton, tennis, and multipurpose courts are never treated as confirmed pickleball venues.'}</p></>}
    {view === 'opening' && <>{chart(['weekdays', 'weekends'], (item) => filtered.filter((r) => r.parsedSchedules.some((s) => s.days.includes(item))).length)}<p className="dashboard-message">{zh ? '顯示的時段為從原始文字保守擷取的衍生資訊，請以完整來源文字及學校公告為準；未提供即時開放狀態。' : 'Schedules are conservatively derived from source text. Check the complete source text and school notices; no real-time open status is provided.'}</p></>}
    {view === 'booking' && chart(['official_booking_link', 'booking_information_in_source', 'contact_school', 'unknown'].map((v) => bookingLabel(v as BookingStatus, zh)), (label) => filtered.filter((r) => bookingLabel(r.bookingStatus, zh) === label).length)}
    {view === 'districts' && chart(districts, (item) => filtered.filter((r) => r.districtName === item).length)}
    {view === 'quality' && <div className="quality-grid">{Object.entries(summary?.dataQuality ?? {}).map(([key, value]) => <article key={key}><span>{key}</span><strong>{value.length}</strong></article>)}</div>}
    {view === 'notes' && <div className="dashboard-message"><p>{zh ? '本資料為臺北市立高級中等以下學校的校園場地開放時間公開資訊。運動可能由來源文字偵測；校園開放並不表示可預約，也不保證特定日期、時間、球場、設備、費用或匹克球適用性。請向臺北市教育局、學校或官方預約系統確認實際場地、開放時間、預約程序、費用及使用規則。' : 'This dataset provides campus-opening information for Taipei municipal schools below the tertiary level. Sports may be detected from source text. Campus access does not necessarily mean a venue is reservable or that a particular sports facility is available. Confirm facilities, opening hours, booking procedures, fees, and rules through Taipei City Department of Education, the school, or an official booking system.'}</p></div>}
  </section>;
}
