import { useEffect, useMemo, useState } from 'react';
import type { Language } from '../types';
type RecyclingRecord={year:number;month:number;districtName:string;recyclingTons:number};
const f=(n:number)=>n.toLocaleString(undefined,{maximumFractionDigits:1});
export function RecyclingAnalyticsDashboard({language}:{language:Language}){
 const zh=language==='zh';const[records,setRecords]=useState<RecyclingRecord[]|null>(null);const[year,setYear]=useState(0);const[month,setMonth]=useState(0);const[district,setDistrict]=useState('');const[view,setView]=useState('overview');
 useEffect(()=>{fetch('/data/recycling-analytics/records.json').then(r=>r.json()).then(setRecords).catch(()=>setRecords([]))},[]);
 const years=useMemo(()=>[...new Set((records??[]).map(r=>r.year))].sort((a,b)=>b-a),[records]);const y=year||years[0]||0;const districts=useMemo(()=>[...new Set((records??[]).map(r=>r.districtName).filter(x=>x!=='其他'))],[records]);const rows=useMemo(()=> (records??[]).filter(r=>r.year===y&&(!month||r.month===month)&&(!district||r.districtName===district)),[records,y,month,district]);const total=rows.reduce((n,r)=>n+r.recyclingTons,0);const ms=[...new Set(rows.map(r=>r.month))];const ranking=useMemo(()=>districts.map(d=>[d,rows.filter(r=>r.districtName===d).reduce((n,r)=>n+r.recyclingTons,0)] as const).sort((a,b)=>b[1]-a[1]),[districts,rows]);const trend=useMemo(()=>Array.from({length:12},(_,i)=>i+1).map(m=>[m,(records??[]).filter(r=>r.year===y&&r.month===m&&(!district||r.districtName===district)).reduce((n,r)=>n+r.recyclingTons,0)] as const).filter(x=>x[1]>0),[records,y,district]);const prev=(records??[]).filter(r=>r.year===y-1&&ms.includes(r.month)&&(!district||r.districtName===district)).reduce((n,r)=>n+r.recyclingTons,0);const yoy=prev?((total-prev)/prev)*100:null;
 if(!records)return <p>{zh?'載入資源回收統計中…':'Loading recycling analytics…'}</p>;
 const tabs=[['overview',zh?'資源回收統計':'Recycling Analytics'],['ranking',zh?'行政區排名':'District Ranking'],['trend',zh?'每月趨勢':'Monthly Trend'],['notes',zh?'資料說明':'Data Notes']];return <section className="bulky-dashboard"><nav className="module-view-tabs">{tabs.map(([k,l])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}>{l}</button>)}</nav><div className="bulky-filters"><label>{zh?'年度':'Year'}<select value={y} onChange={e=>setYear(Number(e.target.value))}>{years.map(v=><option key={v}>{v}</option>)}</select></label><label>{zh?'月份':'Month'}<select value={month} onChange={e=>setMonth(Number(e.target.value))}><option value="0">{zh?'全年度':'Full year'}</option>{Array.from({length:12},(_,i)=><option value={i+1} key={i+1}>{i+1}</option>)}</select></label><label>{zh?'行政區':'District'}<select value={district} onChange={e=>setDistrict(e.target.value)}><option value="">{zh?'全臺北市':'All Taipei'}</option>{districts.map(v=><option key={v}>{v}</option>)}</select></label></div>{view==='overview'&&<><div className="dashboard-cards">{[[zh?'選取期間回收量（噸）':'Recycling volume (tonnes)',f(total)],[zh?'月平均回收量':'Monthly average',f(total/Math.max(ms.length,1))],[zh?'回收量最高行政區':'Highest-volume district',ranking[0]?`${ranking[0][0]} — ${f(ranking[0][1])}`:'—'],[zh?'年增率':'YoY',yoy===null?'—':`${yoy>=0?'+':''}${yoy.toFixed(1)}%`]].map(([l,v])=><article key={String(l)}><span>{l}</span><strong>{v}</strong></article>)}</div><p className="dashboard-message">{zh?'資源回收量是清潔隊來源紀錄的總量，不等同回收率、回收效率或行政區環保表現。':'Recycling volume is a source-recorded total, not a recycling rate, efficiency, or environmental performance measure.'}</p></>}{view==='ranking'&&<div className="dashboard-chart">{ranking.map(([d,n],i)=><div className="bar-row" key={d}><span>#{i+1} {d}</span><div><i style={{width:`${n/Math.max(ranking[0]?.[1]||1,1)*100}%`}}/></div><strong>{f(n)}</strong></div>)}</div>}{view==='trend'&&<div className="dashboard-chart">{trend.map(([m,n])=><div className="bar-row" key={m}><span>{m}{zh?'月':' month'}</span><div><i style={{width:`${n/Math.max(...trend.map(x=>x[1]),1)*100}%`}}/></div><strong>{f(n)}</strong></div>)}</div>}{view==='notes'&&<p className="dashboard-message">{zh?'資料來源：臺北市資料大平臺／臺北市政府環境保護局。本模組分析清潔隊各區月度回收量，非回收站位置；跨年比較僅使用兩年皆有的相同月份。':'Source: Taipei Open Data / Taipei City Department of Environmental Protection. This module analyzes district-team monthly recycling volume, not recycling-station locations; year comparisons use only months available in both years.'}</p>}</section>;
}
