import { useEffect, useMemo, useState } from 'react';
import type { Language, UnusedMedicineCollectionStationRecord } from '../types';

type View = 'overview' | 'districts' | 'categories' | 'directory' | 'quality' | 'notes';
type Summary = { dataQuality: Record<string, unknown[]> };
const EMPTY = '—';

export function UnusedMedicineCollectionStationsDashboard({ language }: { language: Language }) {
  const zh = language === 'zh';
  const [records, setRecords] = useState<UnusedMedicineCollectionStationRecord[] | null>(null);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [view, setView] = useState<View>('overview');
  const [district, setDistrict] = useState(''); const [category, setCategory] = useState(''); const [phoneOnly, setPhoneOnly] = useState(false); const [addressOnly, setAddressOnly] = useState(false); const [search, setSearch] = useState(''); const [sort, setSort] = useState<'stationName' | 'districtName' | 'stationCategory'>('stationName'); const [page, setPage] = useState(1);

  useEffect(() => {
    fetch('/data/unused-medicine-collection-stations/records.json').then((r) => r.ok ? r.json() : Promise.reject()).then(setRecords).catch(() => setRecords([]));
    fetch('/data/unused-medicine-collection-stations/summary.json').then((r) => r.ok ? r.json() : Promise.reject()).then(setSummary).catch(() => setSummary(null));
  }, []);

  const districts = useMemo(() => [...new Set((records ?? []).map((r) => r.districtName).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const categories = useMemo(() => [...new Set((records ?? []).map((r) => r.stationCategory).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const filtered = useMemo(() => (records ?? []).filter((r) => !district || r.districtName === district).filter((r) => !category || r.stationCategory === category).filter((r) => !phoneOnly || r.hasPhone).filter((r) => !addressOnly || Boolean(r.address)).filter((r) => !search || [r.stationName, r.stationCategory, r.districtName, r.address, r.fullPhone].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a, b) => a[sort].localeCompare(b[sort], 'zh-Hant')), [records, district, category, phoneOnly, addressOnly, search, sort]);
  const stats = useMemo(() => ({ stations: filtered.length, names: new Set(filtered.map((r) => r.stationName).filter(Boolean)).size, districts: new Set(filtered.map((r) => r.districtName).filter(Boolean)).size, categories: new Set(filtered.map((r) => r.stationCategory).filter(Boolean)).size, phones: filtered.filter((r) => r.hasPhone).length, addresses: filtered.filter((r) => r.address).length }), [filtered]);
  const topDistrict = useMemo(() => [...new Set(filtered.map((r) => r.districtName).filter(Boolean))].map((name) => ({ name, count: filtered.filter((r) => r.districtName === name).length })).sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'zh-Hant'))[0]?.name ?? EMPTY, [filtered]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / 10)); const pageRows = filtered.slice((Math.min(page, totalPages) - 1) * 10, Math.min(page, totalPages) * 10); const resetPage = () => setPage(1);
  const tabs: Array<[View, string]> = [['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['categories', zh ? '站點類別' : 'Station Categories'], ['directory', zh ? '檢收站清單' : 'Collection Station Directory'], ['quality', zh ? '資料品質' : 'Data Quality'], ['notes', zh ? '資料說明' : 'Data Notes']];
  const copy = (value: string) => navigator.clipboard?.writeText(value);
  const download = () => { const escape = (value: string) => `"${value.replace(/"/g, '""')}"`; const csv = [[zh ? '檢收站名稱' : 'Station name', zh ? '類別' : 'Category', zh ? '行政區' : 'District', zh ? '地址' : 'Address', zh ? '電話' : 'Phone', zh ? '分機' : 'Extension'], ...filtered.map((r) => [r.stationName, r.stationCategory, r.districtName, r.address, r.phone, r.extension])].map((row) => row.map(escape).join(',')).join('\r\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8' })); anchor.download = 'unused-medicine-collection-stations.csv'; anchor.click(); URL.revokeObjectURL(anchor.href); };
  const chart = (items: string[], count: (item: string) => number) => <div className="dashboard-chart">{items.map((item) => <div className="bar-row" key={item}><span>{item}</span><div><i style={{ width: `${(count(item) / Math.max(filtered.length, 1)) * 100}%` }} /></div><strong>{count(item)}</strong></div>)}</div>;

  if (!records) return <section className="bulky-dashboard"><p>{zh ? '載入資料中…' : 'Loading data…'}</p></section>;
  return <section className="bulky-dashboard" aria-label={zh ? '廢棄藥物檢收站' : 'Unused Medicine Collection Stations'}>
    <nav className="module-view-tabs">{tabs.map(([key, label]) => <button key={key} type="button" className={view === key ? 'active' : ''} aria-pressed={view === key} onClick={() => setView(key)}>{label}</button>)}</nav>
    <div className="bulky-filters">
      <label>{zh ? '行政區' : 'District'}<select value={district} onChange={(e) => { setDistrict(e.target.value); resetPage(); }}><option value="">{zh ? '全部' : 'All'}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label>
      <label>{zh ? '類別' : 'Category'}<select value={category} onChange={(e) => { setCategory(e.target.value); resetPage(); }}><option value="">{zh ? '全部' : 'All'}</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label>
      <label>{zh ? '搜尋' : 'Search'}<input value={search} onChange={(e) => { setSearch(e.target.value); resetPage(); }} placeholder={zh ? '站名、類別、行政區、地址或電話' : 'Name, category, district, address, or phone'} /></label>
      <label className="checkbox-label"><input type="checkbox" checked={phoneOnly} onChange={(e) => { setPhoneOnly(e.target.checked); resetPage(); }} />{zh ? '有電話' : 'Has phone'}</label>
      <label className="checkbox-label"><input type="checkbox" checked={addressOnly} onChange={(e) => { setAddressOnly(e.target.checked); resetPage(); }} />{zh ? '有地址' : 'Has address'}</label>
      <button type="button" onClick={download}>{zh ? '下載篩選 CSV' : 'Download filtered CSV'}</button>
    </div>
    {view === 'overview' && <div className="dashboard-cards">{[[zh ? '檢收站總數' : 'Total collection stations', stats.stations], [zh ? '不重複站名' : 'Unique station names', stats.names], [zh ? '涵蓋行政區' : 'Districts covered', stats.districts], [zh ? '站點類別' : 'Station categories', stats.categories], [zh ? '有電話紀錄' : 'Records with phone numbers', stats.phones], [zh ? '有地址紀錄' : 'Records with addresses', stats.addresses], [zh ? '最多站點行政區' : 'District with most stations', topDistrict]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div>}
    {view === 'districts' && chart(districts, (item) => filtered.filter((r) => r.districtName === item).length)}
    {view === 'categories' && <>{chart(categories, (item) => filtered.filter((r) => r.stationCategory === item).length)}<div className="quality-grid"><article><span>{zh ? '有電話' : 'With phone'}</span><strong>{stats.phones}</strong></article><article><span>{zh ? '無電話' : 'Without phone'}</span><strong>{stats.stations - stats.phones}</strong></article></div></>}
    {view === 'directory' && <><div className="bulky-directory-toolbar"><label>{zh ? '排序' : 'Sort'}<select value={sort} onChange={(e) => { setSort(e.target.value as typeof sort); resetPage(); }}><option value="stationName">{zh ? '站名' : 'Station name'}</option><option value="districtName">{zh ? '行政區' : 'District'}</option><option value="stationCategory">{zh ? '類別' : 'Category'}</option></select></label><span>{filtered.length} {zh ? '筆' : 'records'}</span></div><div className="directory-table-wrap"><table><thead><tr><th>{zh ? '檢收站名稱' : 'Station name'}</th><th>{zh ? '類別' : 'Category'}</th><th>{zh ? '行政區' : 'District'}</th><th>{zh ? '地址' : 'Address'}</th><th>{zh ? '電話' : 'Phone'}</th><th>{zh ? '分機' : 'Extension'}</th><th>{zh ? '地圖查詢' : 'Map lookup'}</th></tr></thead><tbody>{pageRows.map((r) => <tr key={r.id}><td>{r.stationName || EMPTY}</td><td>{r.stationCategory || EMPTY}</td><td>{r.districtName || EMPTY}</td><td>{r.address || EMPTY}{r.address && <button className="copy-button" type="button" onClick={() => copy(r.address)}>{zh ? '複製' : 'Copy'}</button>}</td><td>{r.phone ? <><a href={`tel:${r.phone.replace(/[^\d+]/g, '')}`}>{r.phone}</a><button className="copy-button" type="button" onClick={() => copy(r.fullPhone)}>{zh ? '複製' : 'Copy'}</button></> : EMPTY}</td><td>{r.extension || EMPTY}</td><td>{r.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '開啟地圖' : 'Open map'}</a> : EMPTY}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)}>{zh ? '上一頁' : 'Previous'}</button><span>{Math.min(page, totalPages)} / {totalPages}</span><button type="button" disabled={page >= totalPages} onClick={() => setPage(page + 1)}>{zh ? '下一頁' : 'Next'}</button></div></>}
    {view === 'quality' && <div className="quality-grid">{Object.entries(summary?.dataQuality ?? {}).map(([key, value]) => <article key={key}><span>{key}</span><strong>{value.length}</strong></article>)}</div>}
    {view === 'notes' && <div className="dashboard-message"><p>{zh ? '本資料為臺北市居家用藥安全檢查暨廢棄藥物檢收站名單之公開資訊，僅供查詢參考，不代表即時營運狀態、目前受理情形、所有藥品或醫療廢棄物皆可收受、到府服務、費用、處理結果、藥師在場或醫療建議。造訪前請向站點或臺北市政府衛生局確認目前服務。' : 'This dataset is a public directory of Taipei stations offering home medication-safety checks and collection of unused medicines. It does not represent real-time operating status, current acceptance, acceptance of every medicine or medical waste item, home visits, fees, disposal outcomes, pharmacist availability, or medical advice. Confirm current services with the station or Taipei City Department of Health before visiting.'}</p></div>}
  </section>;
}
