import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import iconv from 'iconv-lite';
import Papa from 'papaparse';
import type { IndustrialWasteReuseOperatorRecord } from '../src/types';
type Row=Record<string,string|undefined>;
const raw=resolve('data/raw/industrial-waste-reuse-operators/source.csv'); const output=resolve('public/data/industrial-waste-reuse-operators');
const districts=['松山區','信義區','大安區','中山區','中正區','大同區','萬華區','文山區','南港區','內湖區','士林區','北投區'];
const clean=(v:unknown)=>String(v??'').replace(/[\r\n]+/g,' ').replace(/\s+/g,' ').trim(); const f=(r:Row,h:string)=>clean(r[h]); const split=(v:string)=>/[、；;，,\n]/.test(v)?v.split(/[、；;，,\n]+/).map(clean).filter(Boolean):v?[v]:[];
const quantity=(v:string)=>/^\d+(?:\.\d+)?$/.test(v.replace(/[\s,公噸/月]/g,''))?Number(v.replace(/[\s,公噸/月]/g,'')):null;
const date=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)?v:null;
export function convertIndustrialWasteReuseOperatorRows(rows:Row[]){ const seen=new Set<string>(); const records:IndustrialWasteReuseOperatorRecord[]=[]; const quality={duplicateRows:[] as number[],missingOperatorNames:[] as number[],missingControlNumbers:[] as number[],malformedPhones:[] as number[],missingAddresses:[] as number[],unresolvedDistricts:[] as number[],invalidQuantities:[] as number[],invalidVerificationDates:[] as number[],expiryBeforePassed:[] as number[],unknownWholesaleRetail:[] as number[],noWasteOrPurpose:[] as number[]}; rows.forEach((r,i)=>{const n=i+2,sourceSequenceNumber=f(r,'項次'),controlNumber=f(r,'管制編號'),operatorName=f(r,'機構名稱'),phone=f(r,'機構電話'),address=f(r,'機構地址'),reusableWasteRaw=f(r,'再利用廢棄物'),maximumMonthlyReuseRaw=f(r,'最大月再利用量（公噸/月）'),wasteSourceRaw=f(r,'廢棄物來源'),reusePurposeRaw=f(r,'再利用用途'),verificationPassedDateRaw=f(r,'檢核通過日期'),verificationExpiryDateRaw=f(r,'檢核到期日期'),wholesaleRetailRaw=f(r,'批發零售業'),key=JSON.stringify(r);if(seen.has(key)){quality.duplicateRows.push(n);return}seen.add(key);const maximumMonthlyReuseTonnes=quantity(maximumMonthlyReuseRaw),verificationPassedDate=date(verificationPassedDateRaw),verificationExpiryDate=date(verificationExpiryDateRaw),districtName=districts.find(d=>address.includes(d))??'';if(!operatorName)quality.missingOperatorNames.push(n);if(!controlNumber)quality.missingControlNumbers.push(n);if(!address)quality.missingAddresses.push(n);if(!districtName)quality.unresolvedDistricts.push(n);if(phone&&!/^0\d{1,3}-?\d{6,8}$/.test(phone))quality.malformedPhones.push(n);if(maximumMonthlyReuseRaw&&maximumMonthlyReuseTonnes===null)quality.invalidQuantities.push(n);if((verificationPassedDateRaw&&!verificationPassedDate)||(verificationExpiryDateRaw&&!verificationExpiryDate))quality.invalidVerificationDates.push(n);if(verificationPassedDate&&verificationExpiryDate&&verificationExpiryDate<verificationPassedDate)quality.expiryBeforePassed.push(n);if(!['是','否'].includes(wholesaleRetailRaw))quality.unknownWholesaleRetail.push(n);if(!reusableWasteRaw&&!reusePurposeRaw)quality.noWasteOrPurpose.push(n);records.push({id:`${controlNumber||'row'}-${reusableWasteRaw||n}-${verificationExpiryDateRaw}`,sourceSequenceNumber,controlNumber,operatorName,phone,address,districtName,reusableWasteRaw,reusableWasteCategories:split(reusableWasteRaw),wasteSourceRaw,wasteSourceCategories:split(wasteSourceRaw),reusePurposeRaw,reusePurposeCategories:split(reusePurposeRaw),maximumMonthlyReuseRaw,maximumMonthlyReuseTonnes,verificationPassedDateRaw,verificationPassedDate,verificationExpiryDateRaw,verificationExpiryDate,wholesaleRetailRaw,wholesaleRetailCategory:wholesaleRetailRaw,hasPhone:Boolean(phone),hasAddress:Boolean(address),googleMapsQuery:address||operatorName})});return {records,summary:{totalRecords:records.length,uniqueOperators:new Set(records.map(r=>r.operatorName)).size,quality}} }
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) { const text=existsSync(raw)?iconv.decode(readFileSync(raw),'cp950'):'';const result=convertIndustrialWasteReuseOperatorRows(Papa.parse<Row>(text,{header:true,skipEmptyLines:true,transform:clean,transformHeader:clean}).data);mkdirSync(output,{recursive:true});writeFileSync(resolve(output,'records.json'),JSON.stringify(result.records,null,2));writeFileSync(resolve(output,'summary.json'),JSON.stringify(result.summary,null,2));console.log(`Wrote ${result.records.length} industrial-waste reuse operators.`); }
